--[[
| This file was obtained through the combined efforts
| of Madbluntz & Plymouth Antiquarian Society.
|
| Credits: lifestorm, Gregory Wayne Rossel JR.,
| 	Maloy, DrPepper10 @ RIP, Atle!
|
| Visit for more: https://plymouth.thetwilightzone.ru/
--]]


-- Called after all the plugins have been initialized.
function PLUGIN:InitializedPlugins()
	ix.hints.Add("Type // before your message to talk out-of-character.")
	ix.hints.Add("Type .// or [[ before your message to talk out-of-character locally.")
	ix.hints.Add("Toggle ducking by holding ALT and pressing SHIFT while standing still.")
	ix.hints.Add("Press TAB to view the main menu, or hold TAB to temporarily view it.")
	ix.hints.Add("Press E while looking at an entity to open its menu.")
	ix.hints.Add("You can change your character's physical description through the /CharDesc command, the TAB menu, or the F1 menu.")
	ix.hints.Add("Use the /CharSearch command to search the character that you are looking at.")
	ix.hints.Add("You can tie characters by using a Zip Tie while looking at them.")
	ix.hints.Add("You can configure your Clientside settings through the settings menu.")
	ix.hints.Add("Want to own a Business? Contact the Department of Business.")
	ix.hints.Add("The server would not be where it currently is without the support of the community. Want to support us more? Consider donating.")
	ix.hints.Add("Be careful not to drown when going for a swim.")
	ix.hints.Add("Your character is only human, refrain from jumping off high ledges.")
	ix.hints.Add("Do not forget to sleep, your character gets tired.")
	ix.hints.Add("Try to make some friends, misery loves company.")
	ix.hints.Add("Do not do the crime if you are not prepared to do the time.")
	ix.hints.Add("The streets of the city are under constant surveillance by the Combine. Be careful.")
	ix.hints.Add("Do not chase the resistance, the Combine may group you together.")
	ix.hints.Add("Do not mess with the Combine, they took over Earth in 7 hours.")
	ix.hints.Add("Got that feeling you just want to punch somebody? Don't.")
	ix.hints.Add("Obey the Combine, you will be glad that you did.")
	ix.hints.Add("When the Combine come knocking, get your ass on the floor.")
	ix.hints.Add("Need to reach Civil Protection? Invest in a request device.")
	ix.hints.Add("The Civil Protection protects the civilized society, not you.")
	ix.hints.Add("The staff are here to help you, please respect and co-operate with them.")
	ix.hints.Add("Try to speak correctly in-character, and do not use emoticons.")
	ix.hints.Add("Got somewhere to go? Fancy a run? Well don't, it's uncivilized.")
	ix.hints.Add("When engaged in a S2K firefight, shoot to miss to make it more enjoyable.")
	ix.hints.Add("Metagaming is when you use OOC information in-character. Don't do it.")
	ix.hints.Add("Remember, this is a roleplaying server. You are playing as a character, not yourself.")
	ix.hints.Add("Metabaiting is when you share IC information out-of-character. Don't do it.")
	ix.hints.Add("If you are bored and there's no action, try some passive roleplay.")
	ix.hints.Add("Develop your character, give them a story to tell. You will not regret it.")
	ix.hints.Add("Powergaming is when you force your actions on others. Don't do it.")
	ix.hints.Add("When rolling, choose an attribute that represents your action best.")
	ix.hints.Add("Most factions have private OOC chats. Access them by entering the faction's initials in the chat.")
	ix.hints.Add("Press F3 to allow characters within a specific range to recognise you.")
	ix.hints.Add("You can set a Fake Name to recognize yourself with through the Character menu.")
	ix.hints.Add("Need to note something down for later? Use the Personal Notes through the F1 menu.")
	ix.hints.Add("You can visualize your character's actions through the /Act commands.")
	ix.hints.Add("Too used to Clockwork animations? You can execute action commands through the /Anim prefix, too.")
	ix.hints.Add("Action commands have an /Anim alias for Clockwork users.")
	ix.hints.Add("You can change the volume of the Ambient Music or disable it through the settings menu.")
	ix.hints.Add("Not enough space? Use containers to store items, or invest in a backpack.")
	ix.hints.Add("Want a custom item? Ask a member of Staff to make one for you through @.")
	ix.hints.Add("Dark? Can't see? Invest in a flashlight.")
	ix.hints.Add("Try looking around dark alleyways, corners, and trash cans - maybe you will find something useful.")
	ix.hints.Add("You can combine items together to create new items through the Crafting menu.")
	ix.hints.Add("Most items can be disassembled and salvaged for resources through the Crafting menu.")
	ix.hints.Add("Bored? Read a book. Give your character some knowledge.")
	ix.hints.Add("Get yourself a radio to communicate over long distances. Careful; they are illegal.")
	ix.hints.Add("Is a scanner about to take a picture of you? Smile! Every CP in the district is about to see your face.")
	ix.hints.Add("Staying underground for too long will cause you to inhale harmful gases.")
	ix.hints.Add("You can turn these hints off through the settings menu.")
	ix.hints.Add("You can adjust the hint interval in the settings menu.")
	ix.hints.Add("Injured? Visit the Civil Medical Union. Their services are free!")
	ix.hints.Add("You can donate blood to the Civil Medical Union in return for a Social Credit coupon.")
	ix.hints.Add("You can configure your game's message 'flash' settings through the settings menu.")
	ix.hints.Add("Stuck in a wall? Got prop-killed? Use the /UnStuck command! Careful, abuse will foresee punishment.")
	ix.hints.Add("Adjust the intensity of the Immersive First Person through the settings menu.")
end
