--[[
| This file was obtained through the combined efforts
| of Madbluntz & Plymouth Antiquarian Society.
|
| Credits: lifestorm, Gregory Wayne Rossel JR.,
| 	Maloy, DrPepper10 @ RIP, Atle!
|
| Visit for more: https://plymouth.thetwilightzone.ru/
--]]

-- example: ix.city:AddDisallowment("comp_plastic")
ix.city:AddDisallowment("apartmentkey")
ix.city:AddDisallowment("shopkey")
ix.city:AddDisallowment("legs_black_padded_pants")
ix.city:AddDisallowment("legs_blue_padded_pants")
ix.city:AddDisallowment("legs_green_padded_pants")
ix.city:AddDisallowment("torso_green_rebel_uniform")
ix.city:AddDisallowment("torso_blue_rebel_uniform")
ix.city:AddDisallowment("torso_medical_rebel_uniform")
ix.city:AddDisallowment("torso_blue_kevlar")
ix.city:AddDisallowment("torso_green_kevlar")
ix.city:AddDisallowment("torso_green_kevlar_t3")
ix.city:AddDisallowment("torso_medical_kevlar")
ix.city:AddDisallowment("torso_green_kevlar_t2")
ix.city:AddDisallowment("combine_card")
ix.city:AddDisallowment("id_card")
ix.city:AddDisallowment("fake_id_card")
ix.city:AddDisallowment("dummy_smallbomb")
ix.city:AddDisallowment("dummy_mediumbomb")
ix.city:AddDisallowment("dummy_biolock_expar2")
ix.city:AddDisallowment("dummy_biolock_ar2")
ix.city:AddDisallowment("dummy_biolock_ociw")
ix.city:AddDisallowment("dummy_biolock_sr1")
ix.city:AddDisallowment("dummy_emp")
ix.city:AddDisallowment("dummy_largebomb")
ix.city:AddDisallowment("dummy_littlebomb")
ix.city:AddDisallowment("funnybugbait")
ix.city:AddDisallowment("trash_biolock")
ix.city:AddDisallowment("cmbkey")
ix.city:AddDisallowment("militarykey")
ix.city:AddDisallowment("customitem_m")
ix.city:AddDisallowment("customitem_s")
ix.city:AddDisallowment("customitem_l")
ix.city:AddDisallowment("customitem_xl")
ix.city:AddDisallowment("itemlabel")
ix.city:AddDisallowment("vendingmachinekey")
ix.city:AddDisallowment("fake_id_card_creator")
ix.city:AddDisallowment("shackleskey")
ix.city:AddDisallowment("newspaper_printer_cracked")
ix.city:AddDisallowment("ing_xen_extract")
ix.city:AddDisallowment("ic_cluster_hive")
ix.city:AddDisallowment("ic_coarctate_mucus")
ix.city:AddDisallowment("ic_thanarok_embryo")
ix.city:AddDisallowment("ic_thanatos_embryo")
ix.city:AddDisallowment("ic_nosos_heart")
ix.city:AddDisallowment("tool_chembench")
ix.city:AddDisallowment("tool_metalbench")
ix.city:AddDisallowment("tool_oven")
ix.city:AddDisallowment("tool_oven_rusty")
ix.city:AddDisallowment("tool_mixer")
ix.city:AddDisallowment("tool_creammachine")
ix.city:AddDisallowment("tool_craftingbench")
